### PR TITLE
US2-16 branch

### LINKED ISSUE #23: US16 - As a user I want to be able to save my game at any point in the 16 rounds so that I can load my save later.

### LINKED ISSUE #41: US2 - As a user, I want to be able to save my progress of the game so that I can come back to it in the future

### PR DESCRIPTION
**Pull request by claris0911**
Fixes #41 and fixed #23

### CODE REVIEW

**Comment by amanda-chan** [comment]
Save score missing from function for US2 😮

**Comment by claris0911** [comment]
after discussing with megan the score fn, the score will be produced off the grid so no need to store the score

**Comment by claris0911** [comment]
image
dk why the tests didnt pass here tho :<

**Review by amanda-chan — APPROVED** [review]
ohh I see :o functions and testing looks good then (๑•̀ㅂ•́)و✧

**Comment by claris0911** [comment]
codes integrated close branch :D

**Pull request closed without merging**
