### PR TITLE
US1 Display game map function 

### PR DESCRIPTION
**Pull request by claris0911**
Issue #42 start new game

### CODE REVIEW

**Review by amanda-chan — APPROVED** [review]
Function and testing looks good 👍

**Comment by huanhuiying** [comment]
The test case for US1 will be coming along too after some refinement to be made 😊

**Review by huanhuiying — APPROVED** [review]

**Review by meganpng — APPROVED** [review]
Looks good, code makes sense

**Comment by claris0911** [comment]
TDD file:
[US1-TestCase.xlsx](https://github.com/huanhuiying/DevOps_Oct2021_Team-5/files/7687460/US1-TestCase.xlsx)

**Pull request merged**
