### PR TITLE
US7 and US8 

### PR DESCRIPTION
**Pull request by claris0911**
Codes for #28 and #38 for review. unit test also included

### CODE REVIEW

**Review by meganpng — APPROVED** [review]
Code approved

**Comment by amanda-chan** [comment]
US 7 and US 8 function and testing looks good 👍

**Review by amanda-chan — APPROVED** [review]
US 7 and US 8 function and testing looks good 👍

**Comment by claris0911** [comment]
have added US7 and 8 into main branch

**Pull request merged**
