### PR TITLE
US20 ExitToMainMenuAfterGameEnd

### PR DESCRIPTION
**Pull request by meganpng**
Please review exit function, I put Hui Ying's code into a function so I can call it, changes can be made

### CODE REVIEW

**Review by amanda-chan — CHANGES_REQUESTED** [review]
Please update the code with Hui Ying's and the main_menu and configure_menu functions can be placed above, thanks!

**Review by claris0911 — APPROVED** [review]
👍

**Comment by meganpng** [comment]
[Screenshots of US20 Progress.zip](https://github.com/huanhuiying/DevOps_Oct2021_Team-5/files/7687244/Screenshots.of.US20.Progress.zip)

This are the screenshots of the US20 feature to show my TDD and development

**Review by amanda-chan — APPROVED** [review]
Function and TDD looks good 😄

**Review by huanhuiying — APPROVED** [review]
Okay sure, the test case will have some refinements to be made, I will start with the testing right away once the test case is ready.  😊

**Pull request merged**
