### PR TITLE
US11 & US14

### PR DESCRIPTION
**Pull request by amanda-chan**
Functions and testing #31 and #34, codes have yet to be reviewed

### CODE REVIEW

**Comment by amanda-chan** [comment]
Realized function is written for US11 as well in the same file, hence, edits will be made

**Comment by amanda-chan** [comment]
Commit: "Code developed for US14, tests not passed" was testing for US11 function which did not pass

**Comment by amanda-chan** [comment]
Functions for US 11 and US 14, all tests have passed, please review thanks!

**Review by claris0911 — APPROVED** [review]
all tests passed, code looks good :)

**Comment by claris0911** [comment]
codes from this branch have been merged into main, closing pull request

**Pull request closed without merging**
