### PR TITLE
Approval to close display-game-map branch

### PR DESCRIPTION
**Pull request by claris0911**
refactoring the code structure, close the branch to clean.

### CODE REVIEW

**Review by meganpng — APPROVED** [review]
closing branch approved

**Comment by amanda-chan** [comment]
Good for closing 👍

**Review by amanda-chan — APPROVED** [review]
Good for closing 👍

**Review by huanhuiying — APPROVED** [review]
After understanding this is an extra file is not needed, hence resulting in the cause of deletion of 39 lines of code, it is understood that by approving this request will not affect the current development stage of the project.

**Pull request merged**
