### PR TITLE
US5 - As a user, I want to be able to input a number so that I can select the type of building to place down.

### PR DESCRIPTION
**Pull request by amanda-chan**
Issue #36

### CODE REVIEW

**Comment by amanda-chan** [comment]
[TDD US5.xlsx](https://github.com/huanhuiying/DevOps_Oct2021_Team-5/files/7682796/TDD.US5.xlsx)

**Review by claris0911 — APPROVED** [review]
👍

**Review by meganpng — APPROVED** [review]
The changes made looks good.

**Comment by huanhuiying** [comment]
ok sure, the Test Case for US 5 is in the QA repo too, just need to make some refinement to it 😊.

**Review by huanhuiying — APPROVED** [review]

**Pull request merged**
