### PR TITLE
US 6 and US 12

### PR DESCRIPTION
**Pull request by amanda-chan**
Function and testing for #32 and #37, codes to be reviewed

### CODE REVIEW

**Comment by amanda-chan** [comment]
All tests has passed for US6 and US12 function, please review, thanks!

**Review by meganpng — APPROVED** [review]
code for US6 and 12 approved

**Review by claris0911 — APPROVED** [review]
all tests passed, code looks good 😄

**Comment by claris0911** [comment]
have merged US6 and 12 into main branch

**Comment by claris0911** [comment]
have integrated US6 and 12 codes into main

**Comment by claris0911** [comment]
have integrated this US code with main

**Pull request closed without merging**
