### PR TITLE
Redo"mainMenuFeature US21"

### PR DESCRIPTION
**Pull request by huanhuiying**

### CODE REVIEW

**Review by amanda-chan — APPROVED** [review]
Looks good! 👍

**Review by claris0911 — APPROVED** [review]
looks good :)

**Comment by claris0911** [comment]
i went back and looked again and realised that you accidentally overlapped other user stories. pls redo your code to fit the assigned user story

**Comment by meganpng** [comment]
Do remember to upload the unit testing document for this current change that we have seen in the daily meeting before you proceed to upload a new tdd document for the change that the tech lead wants you to do.

**Comment by huanhuiying** [comment]
Okay sure, I will upload the copy now before I upload the new TDD document, sorry for kept on forgetting about it
[SimpCity US21 TDD V2 .xlsx](https://github.com/huanhuiying/DevOps_Oct2021_Team-5/files/7687164/SimpCity.US21.TDD.V2.xlsx)
.

**Comment by huanhuiying** [comment]
I have done the TDD test for the latest change the tech lead wants me to do. Here is the document
[SimpCity US21 TDD V3.xlsx](https://github.com/huanhuiying/DevOps_Oct2021_Team-5/files/7687175/SimpCity.US21.TDD.V3.xlsx)
.

**Review by claris0911 — APPROVED** [review]
your tdd looks good, also thank you for making changes to the code :) 👍

**Review by amanda-chan — APPROVED** [review]
Both TDD and function looks good 👍

**Review by meganpng — COMMENTED** [review]
Changes that were made were relevant and good, it looks good.

**Review by meganpng — APPROVED** [review]
Changes that were made were relevant and good, it looks good.

**Pull request merged**
