### PR TITLE
US 10

### PR DESCRIPTION
**Pull request by amanda-chan**
Function and testing for #30, codes to be reviewed

### CODE REVIEW

**Review by meganpng — APPROVED** [review]
Codes for US10 approved

**Review by claris0911 — APPROVED** [review]
all tests passed, code looks good :D

**Comment by claris0911** [comment]
have added US10 into main branch

**Comment by claris0911** [comment]
have integrated this US code with main

**Comment by claris0911** [comment]
have integrated this US code with main

**Pull request closed without merging**
